mqtt:
  host: '192.168.8.107'
  port: 1883
  topic: telegram/push_notification
  is_tls: false
  tls_port: 8883
  keep_alive: 30
  qos: 2
  clean_session: False

log:
  file_name: notification
  path: C:\gitlab\telegram-integration\telegram
  level: DEBUG
  retention: '5 days' # "1 week, 3 days", "2 months"
  rotation: '5 MB' # "100 MB", "0.5 GB", "1 month 2 weeks", "4 days", "10h", "monthly", "18:00", "sunday", "w0", "monday at 12:00"

telegram:
  api_id: 22241399
  hash_id: 5d8a24d581e2c1d3c97d06c36e516b19
